version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: kamerka-gui-web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8085:8000
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: kamerka-gui-celeryworker
    command: /start-celeryworker
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
